### ISSUE TITLE
Segfault when calling non-existing method (on `geterror`)

### ISSUE THREAD

**Issue by dfdx** [aviks/JavaCall.jl#8]
Let's take a simple example:

```
julia> using JavaCall
Found libjvm @ /usr/lib/jvm/default-java/jre/lib/amd64/server

julia> JavaCall.init(["-ea", "-Xmx1024M"])
JNINativeInterface(Ptr{Void} @0x0000000000000000...

julia> jlm = @jimport "java.lang.Math"
JavaObject{symbol("java.lang.Math")} (constructor with 2 methods)

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0
```
So code is valid, correct result is returned. 

Now I make an error in method name, calling `sin111` instead of `sin`: 

```
julia> jcall(jlm, "sin111", jdouble, (jdouble,), pi/2)

signal (11): Segmentation fault
unknown function (ip: 732001880)
unknown function (ip: 729411466)
unknown function (ip: 729353813)
geterror at /home/<username>/.julia/v0.3/JavaCall/src/JavaCall.jl:215
jcall at /home/<username>/.julia/v0.3/JavaCall/src/JavaCall.jl:233
jl_apply_generic at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
...
```
Julia halts due to segmentation fault. Same error occurs even if method name is correct, but types of parameters are wrong, e.g. if we call `jcall(jlm, "sin", jint, (jdouble,), pi/2)`

For reference, error happens in `geterror` function, specifically on line: 
```
res = ccall(jnifunc.CallObjectMethod, Ptr{Void}, (Ptr{JNIEnv}, Ptr{Void}, Ptr{Void}), penv, jthrow, jmethodId)
```
So looks like a problem with pointers, though I wasn't able to follow all levels of indirection. 

-------

java version "1.7.0_76" (HotSpot 64-Bit Server VM)
julia version 0.3.8
JavaCall version 0.2.2 (commit `39e2ff9358`)

**Comment by aviks** [comment]
Can you please try the latest master (`Pkg.checkout("JavaCall")` and see if this problem still exists? I can't seem to replicate it any more on OSX. 

```julia

              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.9-pre+27 (2015-05-20 15:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 8418a3a* (31 days old release-0.3)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using JavaCall
Loaded /Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home/jre/lib/server/libjvm.dylib

julia> JavaCall.init(["-ea", "-Xmx1024M"])

julia> jlm = @jimport "java.lang.Math"
JavaObject{symbol("java.lang.Math")} (constructor with 2 methods)

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0

julia> jcall(jlm, "sin111", jdouble, (jdouble,), pi/2)
Exception in thread "main" java.lang.NoSuchMethodError: sin111
ERROR: Error calling Java: java.lang.NoSuchMethodError: sin111
 in error at error.jl:21
 in geterror at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:233
 in jcall at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:245

julia> jcall(jlm, "sin", jint, (jdouble,), pi/2)
Exception in thread "main" java.lang.NoSuchMethodError: sin
ERROR: Error calling Java: java.lang.NoSuchMethodError: sin
 in error at error.jl:21
 in geterror at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:233
 in jcall at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:245

julia> jcall(jlm, "sin111", jdouble, (jdouble,), pi/2)
Exception in thread "main" java.lang.NoSuchMethodError: sin111
ERROR: Error calling Java: java.lang.NoSuchMethodError: sin111
 in error at error.jl:21
 in geterror at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:233
 in jcall at /Users/aviks/.julia/v0.3/JavaCall/src/JavaCall.jl:245

```

**Comment by dfdx** [comment]
Still getting this error on my Linux Mint box:

```
signal (11): Segmentation fault
unknown function (ip: 1103799896)
unknown function (ip: 1101209482)
unknown function (ip: 1101151829)
geterror at /home/slipslop/.julia/v0.3/JavaCall/src/JavaCall.jl:227
jcall at /home/slipslop/.julia/v0.3/JavaCall/src/JavaCall.jl:245
jl_apply_generic at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1537335448)
unknown function (ip: 1537331977)
unknown function (ip: 1537398462)
unknown function (ip: 1537401088)
jl_load at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
include at ./boot.jl:245
jl_apply_generic at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
process_options at ./client.jl:285
_start at ./client.jl:354
jlcall__start_17477 at /usr/local/julia03/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200962)
julia_trampoline at /usr/local/julia03/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199805)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199861)
Segmentation fault
```

I tried with both - julia 0.3.8 and newest julia 0.3.9 (with 0.4 package couldn't load). I will try different Java versions as well.

**Comment by dfdx** [comment]
Ok, I found that with OpenJDK 1.7 code above works. I will do some more tests later, but this is already good achievement, thanks. 

None of the Oracle JVMs worked for me, however. Here are all versions I've tried:

 * **OpenJDK 1.7.0_65** -- works
 * Oracle JDK 1.7.0_76 -- crashes
 * Oracle JDK 1.7.0_79 -- crashes
 * Oracle JDK 1.8.0_45 -- crashes

**Comment by waTeim** [comment]
Hmm, what's the 0.4 error message?  Cut-n-paste it?  For in #9, I tested only OpenJDK.

**Comment by dfdx** [comment]
This is with today's nightly build of Julia (0.4.0-dev+5491) and latest master of JavaCall:

```
 $ julia04 -e 'using JavaCall'

WARNING: deprecated syntax "{a,b, ...}" at /home/<username>/.julia/v0.4/JavaCall/src/JavaCall.jl:69.
Use "Any[a,b, ...]" instead.

WARNING: deprecated syntax "{}" at /home/<username>/.julia/v0.4/Memoize/src/Memoize.jl:24.
Use "[]" instead.
ERROR: LoadError: wrong number of arguments
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
 in process_options at ./client.jl:280
 in _start at ./client.jl:404
while loading /home/slipslop/.julia/v0.4/JavaCall/src/JavaCall.jl, in expression starting on line 54
```

Though, I'm not sure error message is correct, because line 54 of `JavaCall.jl` is simply: 

    function findjvm()

Let me know if I can provide any more information.

**Comment by waTeim** [comment]
Hmm is this a updated in 0.3 but need to also update in 0.4 thing?  Try to add/checkout again, because this is precisely the error that is addressed by #9.  BTW the deprecation warning in Memoize is also taken care of in the latest master:

BTW the latest Memoize addresses that deprecation

    julia> Pkg.status()
     - JavaCall                      0.2.2+             master
     - Memoize                       0.0.0+             master

**Comment by dfdx** [comment]
Ah, my mistake - I hadn't actually updated package for Julia 0.4, sorry for misleading. Now, with this configuration fixed, Julia 0.4 can load JavaCall and pass the test above. Moreover, now Julia 0.4 works with both - OpenJDK 1.7 and Oracle JDK 1.7 (but not 1.8). So here's a table of what works and what still doesn't (assuming this time I haven't forgot anything):

|                  | Oracle JDK 1.7 | Oracle JDK 1.8 | OpenJDK 1.7 |
----------------|----------------------|----------------------|--------------------
| Julia 0.3   |       fails              |     fails               |    works          |
| Julia 0.4   |       works           |      fails              |    works

**Comment by waTeim** [comment]
I feel like something subtle is going on here because lines 226 and 227

    if jmethodId==C_NULL; error ("Java Exception thrown, but no details could be retrieved from the JVM"); end
    res = ccall(jnifunc.CallObjectMethod, Ptr{Void}, (Ptr{JNIEnv}, Ptr{Void}, Ptr{Void}), penv, jthrow, jmethodId)

In your example *jmethodId* must be null because it corresponds to a non-existant function.  How is execution even making it to line 227?

**Comment by dfdx** [comment]
I will inspect this code in more detail tomorrow, but from quick test I see that `jmethodId` is _not_ null:

    jmethodId == Ptr{Void} @0x0000000004452eb8

**Comment by aviks** [comment]
This `jmethodId`  refers to the `toString()` method on `java.lang.Throwable`. That's the method we call on the throwable retrieved from the JVM (in this case the `java.lang.NoSuchMethodError`) to get the error message.

**Comment by waTeim** [comment]
Hmm well that's a red herring; sorry for the distraction.  Luckily segfaults are the easiest track down especially on linux using gdb.

**Comment by dfdx** [comment]
Wow, I didn't know gdb has such possibility. Though, I have very little experience with it. Could you please elaborate a little bit more what is a supposed sequence of actions to get useful information? For now I've done only this, probably naive, test:

```
gdb julia
GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
...
(gdb) run
Starting program: /usr/bin/julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.9 (2015-05-30 11:24 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> using JavaCall
Loaded /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so

julia> JavaCall.init(["-ea", "-Xmx1024M"])
[New Thread 0x7fffd8604700 (LWP 28892)]
...

julia> jlm = @jimport "java.lang.Math"
JavaObject{symbol("java.lang.Math")} (constructor with 2 methods)

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0

julia> jcall(jlm, "sin111", jdouble, (jdouble,), pi/2)
jmethodId == Ptr{Void} @0x0000000005a37d28
jthrow == Ptr{Void} @0x00000000026ba680

Program received signal SIGSEGV, Segmentation fault.
0x00007fffdce4f118 in jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) ()
   from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so
(gdb) backtrace
#0  0x00007fffdce4f118 in jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) ()
   from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so
#1  0x00007fffdce5fe79 in jni_CallObjectMethodA () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so
#2  0x00007ffff4d03b72 in ?? ()
#3  0x00000000058ea800 in ?? ()
#4  0x0000000000000008 in ?? ()
#5  0x00007fffffffd3b0 in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb) 
```
Is it helpful? Can I bring any more information?

**Comment by waTeim** [comment]
#1  0x00007fffdce5fe79 in jni_CallObjectMethodA () from /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so
    #2  0x00007ffff4d03b72 in ?? ()
    #3  0x00000000058ea800 in ?? ()

In the callstack, there's all those frames as if the executable is stripped I wonder 0.3.9 julia is stripped, could you check?

    file julia
    file julia-debug

e.g.

    julia-debug: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), for GNU/Linux 2.6.4, dynamically linked (uses shared libs), not stripped

The above is julia when compiled from source.  If julia is stripped and julia-debug is not stripped, then just using julia-debug would provide more info, I think.  Or if it's because of some buffer over-write the error might not happen at all which is also information.

**Comment by waTeim** [comment]
Also, is this Oracle Java that you're attempting to use?  Do you have both Oracle and OpenJDK installed? I'm wondering if 

    Loaded /usr/lib/jvm/default-java/jre/lib/amd64/server/libjvm.so

is correct

**Comment by dfdx** [comment]
> Also, is this Oracle Java that you're attempting to use? Do you have both Oracle and OpenJDK installed? I'm wondering if

It's Oracle JDK 1.7:
```
/usr/lib/jvm $ default-java/bin/java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```
I switch JDKs manually by changing `default-java` symlink to point to what I'm testing. Not the most elegant solution, but it minimizes dependencies. 

> In the callstack, there's all those frames as if the executable is stripped I wonder 0.3.9 julia is stripped, could you check?

Both are not stripped, e.g. for `julia`:
```
/usr/local/julia03 $ file bin/julia
bin/julia: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, not stripped
```

> Or even better debug using compile-from-src julia and include src-code info in gdb, the it will pin-point the line in julia where the crash is happen; harder though.

I feel like I missed the whole C/Linux course in university :) Could you please provide more information on how to do it? I'm building julia v0.3.9 from sources right now, but what should I do after it?

**Comment by waTeim** [comment]
To start off here's [an install directory overview](http://stackoverflow.com/questions/30340010/after-building-julia-from-source-whats-safe-to-delete/30343304#30343304) I didn't find a way (yet) of simply starting julia with gdb -- maybe because of all the dynamic loading, but what you can do it run gdb -p  [here's an example](https://gist.github.com/waTeim/d42dd9a7ec18b39f7a6e)

**Comment by waTeim** [comment]
I'm going to follow [this blog post](http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html) so I can also maintain multiple version.

**Comment by waTeim** [comment]
Though debugging with gdb turned out to not be that useful, I believe I'm close to understanding the cause.

I'm guessing it's because of this:

>
After an exception has been raised, the native code must first clear the exception before making other JNI calls. When there is a pending exception, the JNI functions that are safe to call are:

>
  ExceptionOccurred()
  ExceptionDescribe()
  ExceptionClear()
  ExceptionCheck()
  ReleaseStringChars()
  ReleaseStringUTFChars()
  ReleaseStringCritical()
  Release<Type>ArrayElements()
  ReleasePrimitiveArrayCritical()
  DeleteLocalRef()
  DeleteGlobalRef()
  DeleteWeakGlobalRef()
  MonitorExit()
  PushLocalFrame()
  PopLocalFrame()

**Comment by dfdx** [comment]
Hmm, seems like even with fresh start of julia (without using JavaCall or whatever) C backtrace is incomplete in my case: 

```
 $ sudo gdb -p 5947
GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Loaded symbols for /lib/x86_64-linux-gnu/libpthread.so.0
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...(no debugging symbols found)...done.
...
warning: File "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py
line to your configuration file "/home/slipslop/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/slipslop/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) where
#0  0x00007ffd869693e9 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffd8700174a in uv__epoll_wait (epfd=<optimized out>, events=events@entry=0x7fff7dde0700, nevents=nevents@entry=1024, timeout=timeout@entry=-1)
    at src/unix/linux-syscalls.c:312
#2  0x00007ffd86fffed6 in uv__io_poll (loop=loop@entry=0x7ffd87ea7960 <default_loop_struct>, timeout=-1) at src/unix/linux-core.c:202
#3  0x00007ffd86ff3d07 in uv_run (loop=0x7ffd87ea7960 <default_loop_struct>, mode=UV_RUN_ONCE) at src/unix/core.c:294
#4  0x00007ffd86fc078e in jl_run_once (loop=0x7ffd87ea7960 <default_loop_struct>) at jl_uv.c:247
#5  0x00007ffd8533e8e2 in julia_process_events_17728 () at stream.jl:537
#6  0x00007ffd8533e5ba in julia_wait_17727 () at task.jl:273
#7  0x00007ffd85348122 in julia_wait_18144 () at task.jl:194
#8  0x00007ffd86f25c83 in jl_apply (f=0x1ed35f0, args=0x7fff7dde3df8, nargs=1) at julia.h:982
#9  0x00007ffd86f2a4f4 in jl_apply_generic (F=0x1ed33d0, args=0x7fff7dde3df8, nargs=1) at gf.c:1411
#10 0x00007ffd84c6bcc2 in ?? ()
#11 0x00007ffd87ea8782 in (anonymous namespace)::VZeroUpperInserter::ID () from /home/slipslop/work/playground/julia/usr/bin/../lib/libjulia-debug.so
#12 0x0000000001247710 in ?? ()
#13 0x0000000000000040 in ?? ()
#14 0x00007ffd878209fe in llvm::PMDataManager::recordAvailableAnalysis(llvm::Pass*) () from /home/slipslop/work/playground/julia/usr/bin/../lib/libjulia-debug.so
#15 0x00000000023f6808 in ?? ()
#16 0x00007fff7dde3df0 in ?? ()
#17 0xe392c70100a34b30 in ?? ()
#18 0x00007fff7dde3c00 in ?? ()
#19 0x00007ffd84c3e420 in ?? ()
#20 0x00000000023f6808 in ?? ()
#21 0x0000000000000002 in ?? ()
#22 0xe392c7010c234b30 in ?? ()
#23 0xe397353003c14b30 in ?? ()
#24 0x0000000000000000 in ?? ()
```
I'm a little bit overwhelmed with current projects right now, but can run same test on a different machine in a couple of days if it makes sense.

**Comment by aviks** [comment]
It seems that Julia's signal handling causes the backtrace to be empty.

**Comment by aviks** [comment]
Can you try the latest master and see if that helps? The last checkin fixes https://github.com/aviks/Taro.jl/issues/17 , but I can't replicate this particular bug yet on my machines, so can't say for sure.

**Comment by waTeim** [comment]
Haha it looks like we arrived at the same conclusion almost at the same time. Check out [my post on dev](https://groups.google.com/forum/#!topic/julia-dev/Q_b8EeYB_-E).

**Comment by waTeim** [comment]
that definitely changes things, here's [the gist](https://gist.github.com/waTeim/d6de79dff15cd1f62c11)

**Comment by waTeim** [comment]
That trace is actually private changes and not master.

**Comment by aviks** [comment]
You seem to be getting a segfault just by launching the JVM? That is strange, and concerning. 

Do you get that kind of failure on master? What does your `java -version` say?

**Comment by waTeim** [comment]
don't worry about that.  I've been debugging a lot and it's changed a lot.  That error is a result of init front loading FindClass Throwable and Throwable.toString()

**Comment by waTeim** [comment]
That is closer, but still not quite right.  I've updated the previous gist.

**Comment by waTeim** [comment]
I feel I can continue with my branch as well.  How did you deal with jthe **ni_IsAssignableFrom** problems?

**Comment by waTeim** [comment]
You know what might be happening.  I wonder if Oracle JVM needs more than just libjvm.so

**Comment by aviks** [comment]
I believe the .so contains correct rpaths, and loads its dependencies
automatically. So not sure, but maybe...

**Comment by waTeim** [comment]
Well maybe, but ldd showed pretty much the default.  I saw no rpath info.

    jeffw@bluto:~/java/jdk1.7.0_80/jre/lib/amd64/server$ ls
    libjsig.so  libjvm.so  Xusage.txt
    jeffw@bluto:~/java/jdk1.7.0_80/jre/lib/amd64/server$ ldd libjvm.so 
	     linux-vdso.so.1 =>  (0x00007fff097fe000)
	     libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa93d6e9000)
  	     libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa93d4e5000)
	     libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa93d2c7000)
	     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa93ceff000)
  	     /lib64/ld-linux-x86-64.so.2 (0x00007fa93e875000)

**Comment by waTeim** [comment]
An update; I believe I have a fix for this.  There are probably a number of things, but in my experimentation, I've changed the source so greatly I'm going to have to pick and choose to reincorporate it back into master.  Will take a while, but things are looking good so far.

**Comment by aviks** [comment]
This should now be fixed on master. Could you please verify?

@waTeim Thanks for all your help in debugging this. I think I found a simple fix that makes this issue go away on linux for me, and hence I pushed the change. The important bit is the change from `CallObjectMethod` to `CallObjectMethodA`

**Comment by waTeim** [comment]
yea that was a part of it for sure.

**Comment by dfdx** [comment]
Not yet! On Julia 0.3.10:

```
julia> using JavaCall
Loaded /usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so

julia> JavaCall.init(["-ea", "-Xmx1024M"])

julia> jlm = @jimport "java.lang.Math"
JavaObject{symbol("java.lang.Math")} (constructor with 2 methods)

julia> jcall(jlm, "sin111", jdouble, (jdouble,), pi/2)
ERROR: `gc_enable` has no method matching gc_enable(::Bool)
 in jcall at /home/azhabinski/.julia/v0.3/JavaCall/src/JavaCall.jl:262

julia> 
```

Is `gc_enable(::Bool)` part of the solution or we can safely revert it to older `gc_enable()` for compatibility with Julia 0.3?

**Comment by aviks** [comment]
Did you just do a `Pkg.checkout("JavaCall")` and not a `Pkg.update()` ? If so, can you do a `Pkg.update()` please? 

I think you have an old version of `Compat`, and hence the `gc_enable` error.

**Comment by dfdx** [comment]
That was the problem, thank you!
